### ISSUE TITLE
Angular 17

### ISSUE THREAD

**Issue by getcovered-olivier** [abhinavakhil/iconify-angular#1]
Hi,

I decided to install the package for NG 17 but am getting
```
error NG6002: 'IconModule' does not appear to be an NgModule class.
```

**Comment by abhinavakhil** [comment]
> Hi,
> 
> 
> 
> I decided to install the package for NG 17 but am getting
> 
> ```
> 
> error NG6002: 'IconModule' does not appear to be an NgModule class.
> 
> ```

It only support v16 till now.You can contribute though if you would like to.

**Comment by getcovered-olivier** [comment]
> > Hi,
> > I decided to install the package for NG 17 but am getting
> > ```
> > 
> > error NG6002: 'IconModule' does not appear to be an NgModule class.
> > ```
> 
> It only support v16 till now.You can contribute though if you would like to.

Issued a PR

**Comment by abhinavakhil** [comment]
Updated to version 17. Thanks @getcovered-olivier for the pr, really appreciate it.
